### ISSUE TITLE
View Native Query not available

### ISSUE THREAD

**Issue by Akos90** [mariadb-corporation/mariadb-powerbi#2]
"View native query" is never available even with just opening the table or, after duplicating a column.
![image](https://user-images.githubusercontent.com/8739106/103774455-e1ae1f00-502c-11eb-9f72-cbdfc2c3b9e0.png)

**Comment by ilyagithub1** [comment]
**View Native Query** is disabled by design.

The design follows the recommendation "_Extensions should set this to true._" for the **HideNativeQuery** flag in the [SqlODBC sample](https://github.com/microsoft/DataConnectors/blob/005fd55f03789673a6aa376a00418551d4391453/samples/ODBC/SqlODBC/SqlODBC.pq#L221-L222) by Microsoft.
