### ISSUE TITLE
Cannot use parameters in the grafic UI for configuring the datasource

### ISSUE THREAD

**Issue by tasso85** [mariadb-corporation/mariadb-powerbi#30]
I am currently using version 1.0.7-beta of the connector, since latest version 1.1.X does not include the custom SQL option.

When setting data source parameters, it requires you to hardcode those in the "Data Source" and "Database" field, those are then used as string:

![data source configuration](https://user-images.githubusercontent.com/655560/231680005-c27cd922-5f91-4ae9-bbb0-1dbb4f6628ff.png)

However, once you have setup the datasource, it allows to replace the hardcoded strings with parameters:

![replaced parameters](https://user-images.githubusercontent.com/655560/231680268-12d8644b-e10d-4f00-920b-b14cf08372fd.png)

Once you have replaced the parameters, however, you can no longer use the grafic UI to change the query, as the "Data Source" and "Database" come up empty, and you'd need to hardcode them again, and then replace them again, or work in the Power Query editor.

**Comment by mariadb-AllenHerrera** [comment]
What are you trying to accomplish with custom SQL options and parameters in the datasource definition? Maybe if we understood the use case we can share a better way to accomplish that?

In general I recommend using the certified connector that comes with Power BI instead of using an older beta version of the connector that isn't tested with the latest versions of Power BI. My best guess is that after defining the connection to mariadb, you enter the "query editor" -> "Home" tab -> "Manage Parameters" -> "Add new Parameter" -> Define a parameter example: TableName = proc -> "Advanced Editor" -> now replace the table name with the parameter you defined, example:
Before:
= mysql_Database{[Name="proc",Kind="Table"]}[Data]
After:
= mysql_Database{[Name=""&TableName&"",Kind="Table"]}[Data]


Furthermore, I recommend next time opening a support ticket with your mariadb enterprise account or with microsoft power bi on how to accomplish your goal to get a more timely response/ feedback loop. 

I recommend closing this ticket as its not an issue with the current version of the connector and parameters can be used to dynamically switch the database connection

**Comment by ilyagithub1** [comment]
@tasso85 The phenomenon that you have found is a limitation in Power BI GUI. The GUI does not support parameter binding for custom connectors (including MariaDB), although dynamic binding works if you tweak your M code. If you decide to carry on with a code-based solution, remember to test all parameter values and supply credentials for all data sources that you expect your report to work with.

**Comment by tasso85** [comment]
@mariadb-AllenHerrera 
you said

> In general I recommend using the certified connector that comes with Power BI instead of using an older beta version of the connector that isn't tested with the latest versions of Power BI.

and I would gladly do that if that didn't end up generating an invalid SQL query, as was shown in other issues reported here too (something about invalid syntax in a cast); so the only solution I found is to write my own SQL query, which does not require/perform any automatic casting, which seems to be only possible using the beta connector, as the original one doesn't allow to write your own query.

Anyway, if what I suggested is a limitation of PowerBI UI, I agree that this issue can be closed.
