### ISSUE TITLE
Creating visualization throws "Object reference not set to an instance of an object."

### ISSUE THREAD

**Issue by rhedgpeth** [mariadb-corporation/mariadb-powerbi#5]
When attempting to create a new pie chart visualization Power BI Desktop is throwing a "Object reference not set to an instance of an object" exception. (See exception,txt for full error log)

Step to reproduce:

1.) Clone a repository that is used to populate a MariaDB ColumnStore database:

```bash
git clone https://github.com/mariadb-corporation/dev-example-columnstore-quickstart
```

and walkthrough the steps to set up a new Docker container, create schema, and load data into MariaDB ColumnStore (Community Server).

2.) Within the (containerized) database, execute the following to create a new user, which will be used by Power BI Desktop to connect to MariaDB.

```sql
CREATE USER 'powerbi_user'@'%' IDENTIFIED BY 'Password123!';
GRANT ALL PRIVILEGES ON *.* TO 'powerbi_user'@'%' WITH GRANT OPTION;
```

3.) Within Power BI Desktop use "Get Data" to establish a connection to MariaDB.

4.) Select airlines, airports, and flights tables within the Power BI Navigator window to create models for each.

5.) Create a new 1-Many(*) relationship between `airlines.iata_code` and `flights.carrier` (See relationship.png)

6.) Create a new Pie Chart visualization. Assign `airlines.airline` to **Legend**. Assign `flights.dep_delay` to **Values**. (See visualization_settings.png)

[exception.txt](https://github.com/mariadb-corporation/mariadb-powerbi/files/5869184/exception.txt)
![relationship](https://user-images.githubusercontent.com/4130607/105755648-3993c380-5f11-11eb-94d5-369bd17105f3.PNG)
![visualization_settings](https://user-images.githubusercontent.com/4130607/105755649-3993c380-5f11-11eb-8f93-e455a67e7475.PNG)

**Comment by ilyagithub1** [comment]
@rhedgpeth The issue is not reproducible. At least, not with the amount of information provided. All attempts to reproduce the issue resulted in a Pie Chart working like a charm.

The error log that you attached contains a stack trace of the exception which does not provide enough evidence that the root cause was the Connector.

Could you please enable Diagnostics Logging in Power BI Desktop, reproduce the issue again, zip and send the diagnostics logs?
See [How to generate Power BI Desktop traces?](https://support.biconnector.com/support/solutions/articles/8000082215-how-to-generate-power-bi-desktop-traces-) for instructions.

Also:

- What version of MariaDB ODBC Driver did you use?
