### ISSUE TITLE
Power BI Connect to MySql - error 10060

### ISSUE THREAD

**Issue by Scotto13** [mariadb-corporation/mariadb-powerbi#7]
I have established my MariaDB connection on my pc and when I use it in Power BI I get this error
![image](https://user-images.githubusercontent.com/78163987/106187913-1fe5bc80-615b-11eb-9626-a5e803130815.png)
Can I please get help to resolve this?
Thank you,

**Comment by ilyagithub1** [comment]
@Scotto13 This means it cannot physically connect to the server using TCP socket `billmax:3306`.

- Check that the server name is correct and that it resolves to the correct IP address.
- Check that that the server can be connected remotely using this server name and port from the PC where you run Power BI Desktop.
- You may try using the server's IP address instead of the host name to test socket connectivity.

If that doesn't help and you are absolutely sure that `billmax:3306` is operational, then please use the **Diagnostics** feature of Power BI Desktop to collect and examine the trace logs. There is a lot more details there that might give you a clue why it cannot connect.
